### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by PatSpiegel** [balena/aes-whitebox#1]
It would be very kind of you if you made examples:
1. encrypt/decrypt file
2. encrypt/decrypt string

_PS: Thank you for you work_

**Comment by balena** [comment]
Hi @PatSpiegel . Thanks for your interest in this project. In order to encrypt/decrypt a C++ string, check StackOverflow (https://stackoverflow.com/questions/24458185/encrypt-and-decrypt-string-with-c-openssl-and-aes). There are several modes of operation and I provide CFB/OFB/CTR (find more in https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation). Knowing how to encrypt/decrypt longs strings you will figure out how to encrypt/decrypt files, it's about the same.

**Comment by PatSpiegel** [comment]
As you noticed, I'm still learning, but learning by example is much easier. And at the same time, more people will learn how to use your wonderful library.
